name=Ashley's shader
description=shader made by twlve
version=1.0
author=twlve
passes=composite
clouds.height.min=80
clouds.height.max=120
clouds.density=0.4
ao.radius=0.05
ao.strength=0.5
iris.detection.range=0.15
iris.specular.intensity=0.5